"""Tests for external travel API adapters (Amadeus, Hotelbeds, Google Places)
and NVIDIA NIM LLM service with BudgetGuard enforcement.
"""
from decimal import Decimal
import pytest

from app.services.external.amadeus import AmadeusFlightAdapter, SOURCE_TAG as AMADEUS_TAG
from app.services.external.hotelbeds import HotelbedsAdapter, SOURCE_TAG as HOTELBEDS_TAG
from app.services.external.places import GooglePlacesAdapter, SOURCE_TAG as PLACES_TAG
from app.services.llm import NvidiaNimService
from app.db.packagepro import PackageProDB
from app.db.session import SessionDB
from app.agent.solver import Solver


def test_amadeus_adapter_mock_search():
    adapter = AmadeusFlightAdapter()
    flights = adapter.search_flights(
        destination_city_name="Jaipur",
        departure_date="2026-09-05",
        return_date="2026-09-08",
        origin_city_name="Delhi",
        travelers=2,
    )
    assert len(flights) >= 3
    first = flights[0]
    assert first["source"] == AMADEUS_TAG
    assert first["origin_airport"] == "DEL"
    assert first["destination_airport"] == "JAI"
    assert first["travelers"] == 2
    assert Decimal(first["total_fare"]) > Decimal("0")
    assert first["is_mock"] is True


def test_hotelbeds_adapter_mock_rates(pro: PackageProDB):
    adapter = HotelbedsAdapter(pro)
    hotels = adapter.get_hotel_rates(
        city_id="cty_c07454f1",  # Jaipur
        checkin_date="2026-09-05",
        checkout_date="2026-09-08",
    )
    assert len(hotels) > 0
    first = hotels[0]
    assert first["source"] == HOTELBEDS_TAG
    assert first["nights"] == 3
    assert Decimal(first["rate_per_night"]) > Decimal("0")
    assert Decimal(first["total_cost"]) == Decimal(first["rate_per_night"]) * 3


def test_google_places_adapter_mock():
    adapter = GooglePlacesAdapter()
    poi = adapter.get_verified_poi("Jaipur", "Amber Palace")
    assert poi["source"] == PLACES_TAG
    assert poi["verified"] is True
    assert poi["rating"] >= 4.0
    assert "Jaipur" in poi["formatted_address"]


def test_nvidia_nim_service_multilingual_fallback():
    nim = NvidiaNimService()
    # Offline fallback should produce valid strings in all 4 core languages
    for lang in ["en-IN", "hi", "ta", "te"]:
        plan_exp = nim.explain_plan(language=lang)
        assert len(plan_exp) > 20

        rec_exp = nim.explain_recommendation(
            pkg_name="Jaipur Heritage",
            city_name="Jaipur",
            duration_days=4,
            theme="heritage",
            languages_offered=["hi", "en-IN"],
            traveler_goal="Relaxed cultural trip",
            language=lang,
        )
        assert len(rec_exp) > 20
        # Critical rule: No prices or currency symbols should be generated by LLM
        assert "₹" not in rec_exp
        assert "INR" not in rec_exp


def test_flight_selection_via_budget_guard(client):
    # 1. Create a session with Jaipur package
    req = {
        "city_id": "cty_c07454f1",
        "start_date": "2026-09-05",
        "end_date": "2026-09-08",
        "travelers": 2,
        "budget": {"amount": "30000.00", "currency": "INR"},
        "preferred_languages": ["hi", "en-IN"],
        "theme": "heritage",
        "goal": "Jaipur trip",
    }
    r = client.post("/planner/recommend", json=req)
    assert r.status_code == 200
    session_id = r.json()["session_id"]
    pkg_id = r.json()["recommendations"][0]["package_id"]

    # Select package
    r_sel = client.post(f"/sessions/{session_id}/select-package?package_id={pkg_id}")
    assert r_sel.status_code == 200

    # 2. Get available flights
    r_flt = client.get(f"/sessions/{session_id}/flights")
    assert r_flt.status_code == 200
    flights = r_flt.json()["flights"]
    assert len(flights) > 0

    # 3. Select an expensive flight that exceeds budget cap (cap is 30,000, package is ~21,880)
    expensive_flight = dict(flights[0])
    expensive_flight["total_fare"] = "15000.00"  # 21880 + 15000 = 36880 > 30000

    r_post_flt = client.post(f"/sessions/{session_id}/select-flight", json=expensive_flight)
    assert r_post_flt.status_code == 200
    data = r_post_flt.json()
    # Must be blocked by BudgetGuard!
    assert data["swap_blocked"] is True
    assert data["budget"]["decision"] == "blocked"
    assert Decimal(data["budget"]["overage"]) > Decimal("0")

    # 4. Select an affordable flight that stays under cap
    affordable_flight = dict(flights[0])
    affordable_flight["total_fare"] = "3000.00"  # 21880 + 3000 = 24880 <= 30000
    r_ok_flt = client.post(f"/sessions/{session_id}/select-flight", json=affordable_flight)
    assert r_ok_flt.status_code == 200
    data_ok = r_ok_flt.json()
    assert data_ok.get("swap_blocked") is not True
    assert data_ok["budget"]["decision"] == "approved"
    assert data_ok["selected_flight"]["flight_id"] == affordable_flight["flight_id"]


def test_hotel_selection_endpoint(client):
    req = {
        "city_id": "cty_c07454f1",
        "start_date": "2026-09-05",
        "end_date": "2026-09-08",
        "travelers": 2,
        "budget": {"amount": "50000.00", "currency": "INR"},
        "preferred_languages": ["hi", "en-IN"],
    }
    r = client.post("/planner/recommend", json=req)
    session_id = r.json()["session_id"]
    pkg_id = r.json()["recommendations"][0]["package_id"]
    client.post(f"/sessions/{session_id}/select-package?package_id={pkg_id}")

    # Query hotels
    r_htl = client.get(f"/sessions/{session_id}/hotels")
    assert r_htl.status_code == 200
    hotels = r_htl.json()["hotels"]
    assert len(hotels) > 0

    # Select hotel
    chosen_hotel = hotels[0]
    r_post_htl = client.post(f"/sessions/{session_id}/select-hotel", json=chosen_hotel)
    assert r_post_htl.status_code == 200
    assert r_post_htl.json()["budget"]["decision"] == "approved"
